### ISSUE TITLE
完善文档结构

### ISSUE THREAD

**Issue by Riki-Du** [EZ-hwh/Software-Engineering#35]
从主页的readme.md维护一个树状的文档，希望有如下功能：
1. 用户可以下载本项目后成功运行
2. 介绍Feature，项目完成情况
3. 公布正在进行的工作
4. 一个良好的开发文档，具有引导新加入开发组的成员快速融入团队进行开发的功能，同时帮助现有members梳理整个开发过程。

**Comment by Riki-Du** [comment]
添加了一个参考的结构，还没有补全内容

**Comment by Riki-Du** [comment]
添加了前后端交互以及后端的部分内容。

**Comment by Stephyuka** [comment]
整合了第一阶段全部的开发文档，更新主页的readme文件。

**Comment by Riki-Du** [comment]
希望大家补全前端使用的（跳转。传参）的url的描述信息（就写一句话表示这个路径干嘛的），更新在[这里](https://github.com/EZ-hwh/Software-Engineering/blob/master/documents/url%E6%8E%A5%E5%8F%A3.md)
