### ISSUE TITLE
用况图设计

### ISSUE THREAD

**Issue by Riki-Du** [EZ-hwh/Software-Engineering#41]
目前参考了[这篇博客](https://blog.csdn.net/silenthuang/article/details/30293961)的语法，布局挺丑，不知道有什么用况没加上去，望review.
[目前的图](https://www.processon.com/diagraming/5eb0d1965653bb072153e3e5)

**Comment by ystttttt** [comment]
更改了一个画图方法，在共享空间可以看一下
