### ISSUE TITLE
邮箱验证接口

### ISSUE THREAD

**Issue by ystttttt** [EZ-hwh/Software-Engineering#45]
@EZ-hwh @Riki-Du 邮箱验证接口这边我是想直接这样 我从前端直接传email后端 也不传用户名 然后后端发成功了之后给我回一个flag和一个code 然后我前端直接对上 这样ok嘛 不然的话万一后端建了一个用户 还没有密码啥的 结果别人不注册了的话 直接退出 后端就会有多出来的用户了 
我这边post的参数和url是这样的
![image.png](https://images.zenhubusercontent.com/5e6ef3867c78c820a2cbc662/55c536be-c4dd-4766-b85e-759bc1167d17)
回来的数据就一个flag（bool）还有一个code（string）

**Comment by ystttttt** [comment]
aaa忘记说了 代码要从我的branch下哈！我的branch下面是新滴！

**Comment by Riki-Du** [comment]
目前逻辑：
1. 前端发送邮箱，请求验证码。后端生成验证码并保存在数据库，同时将验证码返回给前端（之后应改为邮箱验证）。（url: getcode)
3. 前端发送验证码至后端，后端进行验证。(url: checkcode)

**Comment by EZ-hwh** [comment]
在我的branch下已经实现了邮箱发送验证码的请求（lifeline_app/backend/email.py）
