### ISSUE TITLE
状态机图设计

### ISSUE THREAD

**Issue by Stephyuka** [EZ-hwh/Software-Engineering#48]
- [x] 用户状态图
- [x] 网页跳转状态图
其他核心类：
- [x] ddl状态图 @chty627 
        需要知道ddl的处理机制：如优先级、如何自定义ddl等
- [ ] 作业状态图 
       @613lys @EZ-hwh 我们现在可以上传作业吗？

**Comment by 613lys** [comment]
> * [x]  用户状态图
> * [x]  网页跳转状态图
>   其他核心类：
> * [ ]  ddl状态图 @chty627
>   需要知道ddl的处理机制：如优先级、如何自定义ddl等
> * [ ]  作业状态图
>   @613lys @EZ-hwh 我们现在可以上传作业吗？

现在还不可以，可能准备到sprint3再尝试实现这个功能了

**Comment by Stephyuka** [comment]
> > * [x]   用户状态图
> > * [x]   网页跳转状态图
> >   其他核心类：
> > * [ ]   ddl状态图 @chty627
> >   需要知道ddl的处理机制：如优先级、如何自定义ddl等
> > * [ ]   作业状态图
> >   @613lys @EZ-hwh 我们现在可以上传作业吗？
> 
> 现在还不可以，可能准备到sprint3再尝试实现这个功能了

ok 我先画上去，后面再完善
