### ISSUE TITLE
主页todaylist需要后端传入的json参数

### ISSUE THREAD

**Issue by chty627** [EZ-hwh/Software-Engineering#52]
"TodayList": [
    ["Algorithm Assignment 3", "2020.5.9 10:30", "Complete 15-2.3,17.1"],
    ["Software Engineer homework","2020.5.9 18:30","Implement the demo website."],
    ["Watch a movie","2020.5.9 24:00","<Spider man>"]
  ],

对于weeklist也是相同的格式：
名字，时间，简介

**Comment by Riki-Du** [comment]
写了一个暂时只有todaylist的接口，传的也不是today的，是所有的，见[数据接口](https://github.com/EZ-hwh/Software-Engineering/blob/master/documents/%E6%95%B0%E6%8D%AE%E6%8E%A5%E5%8F%A3.md)todolist项

**Comment by Riki-Du** [comment]
已提供样例数据

**Comment by ystttttt** [comment]
已经调试完成了 目前都是用的样例数据 数据库操作待更新
